#version: '3.8'

services:
  podcast-app:
    image: fcyber/ai-podcast:latest
    container_name: ai-podcast
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
    restart: unless-stopped